// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/gsuaki/go-echo-graphql/api"
	"github.com/gsuaki/go-echo-graphql/api/rest"
)

// Injectors from wire_mock.go:

func setupMock() (*Server, error) {
	healthHandler := rest.NewHealthHandler()
	router := api.NewRouter(healthHandler)
	server := NewServer(router)
	return server, nil
}

// Injectors from wire_server.go:

func setupServer() (*Server, error) {
	healthHandler := rest.NewHealthHandler()
	router := api.NewRouter(healthHandler)
	server := NewServer(router)
	return server, nil
}
